name = "GenieDeployDocker"
uuid = "a082159f-dd50-4f6d-a3c5-00c38fd36577"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "0.3.1"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieDeploy = "d108a3e0-159a-438b-bbd8-7bf1a8b5a5d1"

[compat]
Genie = "5"
GenieDeploy = "0.1, 1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
