name = "GenieDeployDocker"
uuid = "a082159f-dd50-4f6d-a3c5-00c38fd36577"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
