site_name:        GenieDeployDocker.jl
repo_url:         https://github.com/GenieFramework/GenieDeployDocker.jl
site_description: Deploy Genie Apps with Docker
site_author:      Adrian Salceanu

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
